### ISSUE TITLE
API跳转链接错误打开页面为空

### ISSUE THREAD

**Issue by JujieX** [galacean/galacean.github.io#445]
![image](https://user-images.githubusercontent.com/67930474/184863821-744fea2c-a702-4a30-8333-cca87e88d8bb.png)

![image](https://user-images.githubusercontent.com/67930474/184863785-c88d7283-0e7b-442c-9261-be56b4c9fe77.png)

**Comment by eyworldwide** [comment]
这个是模块名称错了，地址应该是 https://oasisengine.cn/0.8/api/math/Quaternion，我看看怎么修复一下

**Comment by eyworldwide** [comment]
暂时把类型跳转去掉了
