### ISSUE TITLE
官网 API 的体验问题

### ISSUE THREAD

**Issue by cptbtptpbcptdtptp** [galacean/galacean.github.io#716]
- 在 API 页面改路径不能正常跳转

![merge](https://user-images.githubusercontent.com/7768919/233819680-356f0ce9-a99f-4d4c-8d82-1a7895d05f86.gif)

- API 定位到某个具体属性或函数的功能失效了

![image](https://user-images.githubusercontent.com/7768919/233819716-d397910d-d347-4c42-aa61-7bcadd3a3ec9.png)

**Comment by LiMao00** [comment]
整个文档错误好多，全是”Uncaught TypeError: WebGLEngine.create is not a function“这种错误，文档最简单的”绘制一个立方体“都运行不起来，体验极差

**Comment by eyworldwide** [comment]
> 整个文档错误好多，全是”Uncaught TypeError: WebGLEngine.create is not a function“这种错误，文档最简单的”绘制一个立方体“都运行不起来，体验极差

“绘制一个立方体”是能运行的（如下图），请问具体是哪个页面有问题？
<img width="1274" alt="image" src="https://github.com/galacean/galacean.github.io/assets/1296667/1415211a-61e1-412a-9e80-be7e8799b787">

**Comment by cptbtptpbcptdtptp** [comment]
@LiMao00  可能是您的引擎版本与文档版本不匹配，右上角按钮可以切换文档与编辑器的版本
![image](https://github.com/galacean/galacean.github.io/assets/7768919/b5321915-0ca7-4228-8618-968c3bf482b3)
此外，可以参考一下`[概述](https://galacean.antgroup.com/#/docs/latest/cn/start)`中的引擎版本说明了解更多
![image](https://github.com/galacean/galacean.github.io/assets/7768919/8d13acdd-849b-4eec-9bb2-3c806859b6c4)
如果您在创建练习项目时有困难，不妨参考一下我们提供的现成脚手架：
https://github.com/galacean/create-galacean-app
或者可以体验一下编辑器
https://galacean.antgroup.com/editor
如果以上都不能解决您的问题，可以提供引擎版本号与重现 Demo 方便我们定位问题。
