### ISSUE TITLE
官网文档版本切换的 Bug

### ISSUE THREAD

**Issue by cptbtptpbcptdtptp** [galacean/galacean.github.io#775]
有两个问题：

- 在带有示例内容的文档中切换版本，文档的内容随着版本改变了，但是示例的内容并没有变，例如在[绘制一个立方体](https://galacean.antgroup.com/#/docs/0.9/cn/cube)中切换版本到 1.0，因为创建引擎的代码改变了，导致示例直接黑屏
![image](https://github.com/galacean/galacean.github.io/assets/7768919/1924feeb-ba55-4e2b-b2c2-465d9e3a9b20)

- 如果某个文档在 1.0 中存在，但是在 0.9 中不存在，切换的时候
![image](https://github.com/galacean/galacean.github.io/assets/7768919/e018fbe5-f10a-4b7b-bda1-8dfd5e46dd5e)

**Comment by Sway007** [comment]
这个好像是切换版本后前端只刷新了menu列表，没有刷新文档
